# The URL the site will be built for
base_url = "https://quentin-rodriguez.github.io/portio-zola" # todo

#
minify_html = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

#
default_language = "zh"

# The site theme to use.
theme = "portio-zola"

[languages.en]
title = "lhm blog"
generate_feeds = true
build_search_index = false

taxonomies = [
    { name = "tags", feed = true, render = true, paginate_by = 9 },
    { name = "categories", feed = true, render = true, paginate_by = 9 },
]

[languages.en.translations]
showing_all = "Showing All"
see_details = "See Details"
sitemap = "Sitemap"
categories_description = "Showing all posts with the category"
tags_description = "Showing all posts with the tag"
copyright = "All right reserved copyright © Portio 2020"

# Menus
home = "Home"
about = "About"
service = "Service"
work = "Work"
resume = "Resume"
blog = "Blog"

# Sitemaps
about_me = "About me"
frequently_ask_question = "Frequently Ask Question"
privacy_and_policy = "Privacy & Policy"
latest_article = "Latest Article"

[languages.zh]
title = "lhm 博客"
generate_feeds = true
build_search_index = false

taxonomies = [
    { name = "tags", feed = true, render = true, paginate_by = 9 },
    { name = "categories", feed = true, render = true, paginate_by = 9 },
]

[languages.zh.translations]
showing_all = "显示全部"
see_details = "查看详情"
sitemap = "站点地图"
categories_description = "显示该分类下的所有文章"
tags_description = "显示该标签下的所有文章"
copyright = "版权所有 © Portio 2020"

# Menus
home = "首页"
about = "关于"
service = "服务"
work = "作品"
resume = "简历"
blog = "博客"

# Sitemaps
about_me = "关于我"
frequently_ask_question = "常见问题"
privacy_and_policy = "隐私政策"
latest_article = "最新文章"


[extra]
date_format = "%d %B, %Y"
logo = "images/logo.png"
footer_logo = "images/logo.png"
# google_analytics = "YOUR TOKEN FOR GOOGLE ANALYTICS"
display_cta = false

menus = [
  { name = "home", url = "#home" },
  { name = "blog", url = "#blog" },
  { name = "about", url = "#about" },
  { name = "service", url = "#service" },
  { name = "work", url = "#portfolio" },
  { name = "resume", url = "#resume" }
]

sitemaps = [
  { name = "about_me", url = "#about" },
  { name = "frequently_ask_question", url = "#" },
  { name = "privacy_and_policy", url = "#" },
  { name = "latest_article", url = "#" }
]

socials = [
  { icon = "facebook-original", url = "https://www.facebook.com/" },
  { icon = "linkedin-original", url = "https://www.linkedin.com/" },
  { icon = "pinterest", url = "https://www.pinterest.com" },
  { icon = "twitter-original",  url = "https://www.twitter.com" }
]
