title = "关于"
image = "images/about/about-img.jpg"
buttons = [
    ""
]
description = """
  ## 关于我

  享受团队的多样性，在各个领域与他人建立联系、拓展人脉。
"""
content = """
  ### 我设计并构建极致的作品。

  我热爱用户体验与用户界面设计。因为我喜欢解决设计问题，
  并寻找更简单、更优的解决方案。我始终尽力打造兼具最佳
  用户体验的优秀界面。我一直从事视觉设计师的工作。
"""
