title       = "你好，我是 Natasha"
description = """
# 我为你的个人业务助力

享受团队的多样性，在各个领域拓展人脉网络。
"""
button_name = "联系我"
button_url  = "contact"
image       = "images/hero/2960351.jpg"
# video_thumb = "images/hero/popup-thumb.png"
# video_url   = "https://www.youtube.com/embed/tgbNymZ7vqY"
